export default {
    SUCCESS: 'success',
    INFO: 'info',
    ERROR: 'error',


    FIELD_REQUIRED: 'THIS FIELD IS REQUIRED',
    MAX_LIMIT_EXCEED: 'MAXIMUM LIMIT EXCEED',
    ALL_FIELD_REQUIRED: 'ALL FIELDS ARE REQUIRED',

    USER_NOT_AUTHORIZED: 'USER NOT AVAILABLE',

    PARTY_ADDED_SUCCESSFULLY: 'PARTY_ADDED_SUCCESSFULLY',
    PRODUCT_ADDED_SUCCESSFULLY: 'PRODUCT_ADDED_SUCCESSFULLY',
    PARTY_UPDATED_SUCCESSFULLY: 'PARTY_UPDATED_SUCCESSFULLY',

    CANNOT_DELETE_ITEM: 'YOU HAVE NOT AUTHORITY TO DELETE THIS USER',
    CANNOT_REMOVE_FIRST_ITEM: 'YOU CANNOT REMOVE THIS ITEM',
}